REM INSERTING into JOB_HISTORY
Insert into JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (102,to_timestamp('13-JAN-93','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-JUL-98','DD-MON-RR HH.MI.SSXFF AM'),'IT_PROG',60);
Insert into JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (101,to_timestamp('21-SEP-89','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('27-OCT-93','DD-MON-RR HH.MI.SSXFF AM'),'AC_ACCOUNT',110);
Insert into JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (101,to_timestamp('28-OCT-93','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('15-MAR-97','DD-MON-RR HH.MI.SSXFF AM'),'AC_MGR',110);
Insert into JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (201,to_timestamp('17-FEB-96','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('19-DEC-99','DD-MON-RR HH.MI.SSXFF AM'),'MK_REP',20);
Insert into JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (114,to_timestamp('24-MAR-98','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('31-DEC-99','DD-MON-RR HH.MI.SSXFF AM'),'ST_CLERK',50);
Insert into JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (122,to_timestamp('01-JAN-99','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('31-DEC-99','DD-MON-RR HH.MI.SSXFF AM'),'ST_CLERK',50);
Insert into JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (200,to_timestamp('17-SEP-87','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('17-JUN-93','DD-MON-RR HH.MI.SSXFF AM'),'AD_ASST',90);
Insert into JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (176,to_timestamp('24-MAR-98','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('31-DEC-98','DD-MON-RR HH.MI.SSXFF AM'),'SA_REP',80);
Insert into JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (176,to_timestamp('01-JAN-99','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('31-DEC-99','DD-MON-RR HH.MI.SSXFF AM'),'SA_MAN',80);
Insert into JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values (200,to_timestamp('01-JUL-94','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('31-DEC-98','DD-MON-RR HH.MI.SSXFF AM'),'AC_ACCOUNT',90);
