# The environment variable PM_HOME should be set to point to the PowerCenter/PowerMart server install directory

CC=xlC_r
NOSTART=-bnoentry
FLAGS=-+ -q64
DEFINES=-DUNIX -DAIX -D_REENTRANT 
INCLUDEDIRS=-I../include
.SUFFIXES : .cpp
.cpp.o : ;$(CC) -c $(FLAGS) $(DEFINES) $(INCLUDEDIRS) $*.cpp -o $*.o

TARGET=libpmecho.a

OBJS=$(SRCS:%.cpp=%.o)

SRCS= \
SampleExprPlugin.cpp

all : $(TARGET)

$(TARGET) : $(OBJS)
	$(CC) -G $(FLAGS) $(DEFINES) $(INCLUDEDIRS) -o $(TARGET) $(OBJS)
